### ISSUE TITLE
[프로젝트 세팅] 이상민 프로젝트 세팅

### ISSUE THREAD

**Issue by IMWoo94** [f-lab-edu/danggeun#2]
feat. danggeun project setting and issue testing
detail. project spring boot setup
springboot 2.7.14[Gradle - Groovy][Java11]

**Comment by f-lab-ben** [comment]
완료 되었으면 close 하시면 됩니다 ~
(버전 이슈로 순범님 브랜치 머지됐으므로, 이 이슈는 닫아도 되니까요)

**Comment by IMWoo94** [comment]
이슈 close~
버전 낮은 프로젝트 미사용
