### ISSUE TITLE
서버 환경 및 CI/CD

### ISSUE THREAD

**Issue by IMWoo94** [f-lab-edu/danggeun#47]
### NCP ( Naver cloud Platform ) 
- Danggeun Server ( Web Server + WAS )
  -  Nginx
  - SpringBoot ( embedded tomcat ) + Java17
  
- DB Server
  -  MySQL

- Redis Server ( 미 구현 )

---
### jacoco #54 
- 코드 커버리지 적용
- 구문 분석/ 분기 분석 / 전체 코드리지 기준 적용

---
### CI
 - GitAction 활용 하여 main/develop 브랜치에 push or pull request 이벤트 발생 시 Build & Test 가 되도록 반영
 - Build & Test 시 코드 커버리지를 활용하여 품질 향상
   - 코드 커버리지 기준치를 정하여 충족하지 못하는 경우 Build 실패 처리 
   - 코드 커버리지에 대한 정보를 pull request 의 코멘트로 제공하여 공유 

### CD #55 
 - CD 의 경우 main/develop 브랜치에 push 이벤트 발생 시 Jar 파일을 서버에 전달 후 Deploy
 - 현재의 배포의 경우에는 서버가 중단이 되었다가 다시 실행이 되므로 무중단 배포가 아님.

---
### 당근 아키텍처
 
![당근아키텍처](https://github.com/f-lab-edu/danggeun/assets/75981576/0631ae01-8b9b-4fda-a129-affcc1c24344)

참고 wiki : https://github.com/f-lab-edu/danggeun/wiki#%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%84%B1-%EC%A0%95%EB%A6%AC-%EB%A7%81%ED%81%AC

**Comment by f-lab-ben** [comment]
참고하시면 좋을것 같아요

https://uk.devoteam.com/expert-view/api-management-architecture-an-introduction/

https://danmartensen.svbtle.com/exploring-rest-api-architecture

**Comment by f-lab-ben** [comment]
nginx
- reverse proxy
- forward proxy

CI/CD
- git + 배포 스크립트
- jenkins
    - 스케쥴, github 이벤트를 받아서 수행한다
    - 빌드가 실패했을때 처리
    - 빌드의 히스토리를 볼 수 있다 << 
    - 테스트 성공여부를 볼 수 있다 << (gradle build) feature#9-user-join -> develop
    - git 접근을 서버가 직접해야 한다(github public, 서버가 public 접근이 안되면?, 사내망만 접근됨 10.x.x.x, 카카오뱅크 네이버페이, ~~투자증권, 은행권?)
    - 상민님 -> github enterprise, gitlab을 사내에 설치해서 쓰자
    - 3rd party library, <- maven repo, 
    - jenkins 서버 << 여기에 권한을 다 주는것. 얘는 외부망 접근이 가능하다. (특정 hosts -> maven repo, npm repo, github)
    - gradle build -> app.jar ->>> application server 에 전송

자동화 해준다?
빌드 배포
